---
- name: install extra package required by docker (for AUFS)
  apt: pkg=linux-image-extra-{{ ansible_kernel }} update_cache=yes state=present
  tags: [packages]

- name: add docker key to local keychain
  apt_key: url=https://get.docker.io/gpg

# requires pycurl
- name: add docker repository
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present

- name: install docker
  apt: update_cache=yes pkg=lxc-docker state=present

#- name: install buildstep
#  shell: docker build -t progrium/buildstep github.com/progrium/buildstep