---
- include: packages.yml
- include: ruby.yml
- include: nodejs.yml
  sudo: yes
- include: docker.yml
  sudo: yes
- include: hipache.yml
  sudo: yes
- include: ssh.yml
  sudo: yes
#- include: mongodb.yml
#  sudo: yes
- include: postgresql.yml
  sudo: yes
- include: redis.yml
  sudo: yes
