---
- name: create /var/log/dawn for Upstart
  sudo: yes
  file: path=/var/log/dawn
        owner={{ user_main }}
        state=directory

- name: install userspace packages
  apt: update_cache=yes pkg={{ item }} state=present
  tags: [packages]
  with_items:
    - curl
    - git
    - python-pycurl # needed for apt_repo

- include: ruby.yml
- include: docker.yml

- name: spin up redis-hipache
  command: docker run -d -p 6379:6379 --name redis-hipache shipyard/redis

- name: spin up hipache
  command: docker run -d -p 80:80 --name hipache --link redis-hipache:redis shipyard/router

- name: spin up postgres
  command: docker run -d -p 5432:5432 -e POSTGRESQL_USER=dawn -e POSTGRESQL_PASS=dawn --name postgres orchardup/postgresql

- name: spin up redis-logplex
  command: docker run -d -p 6733:6379 --name redis-logplex shipyard/redis

- name: spin up logplex
  command: docker run -d -p 8001:8001 -p 8601:8601 --name logplex -h logplex --link redis-logplex:redis dawn/logplex

- name: generate ssh key for gitreceived
  command: ssh-keygen -t rsa -N "" -f git.key chdir={{ app_path }}/gitreceived creates={{ app_path }}/gitreceived/git.key

- name: spin up gitreceived
  command: docker run -d -p 2201:22 --name gitreceived -v=/var/run/docker.sock:/var/run/docker.sock -e SSH_PRIVATE_KEYS="$(cat {{ app_path }}/git.key)" dawn/gitreceived
