---
- include: packages.yml
- include: ruby.yml
- include: nodejs.yml
- include: docker.yml
- include: hipache.yml
- include: ssh.yml
- include: postgresql.yml
- include: redis.yml
- shell: ls /usr/lib/kerl/
  register: ls_kerl