---
- name: upgrade packages
  apt: upgrade=yes update_cache=yes
  tags: [skip,upgrade]

- name: install userspace packages
  apt: pkg={{ item }} state=present
  tags: [packages]
  with_items:
    - curl
    - git
    - python-pycurl # needed for apt_repo

- name: replace the sshd_config
  copy: src=sshd_config dest=/etc/ssh/sshd_config

- include: ruby.yml
- include: docker.yml

- name: spin up redis-hipache
  command: docker run -d -p 6379:6379 --name redis-hipache shipyard/redis

- name: spin up hipache
  command: docker run -d -p 80:80 --name hipache --link redis-hipache:redis shipyard/router

- name: spin up postgres
  command: docker run -d -p 5432:5432 -e POSTGRESQL_USER=dawn -e POSTGRESQL_PASS=dawn --name postgres orchardup/postgresql

