---
- name: upgrade packages
  apt: upgrade=yes update_cache=yes
  tags: [skip]
  sudo: true

- name: install userspace packages
  sudo: yes
  apt: pkg={{ item }} state=present
  tags: [packages]
  with_items:
    - curl
    - git
    - python-pycurl # needed for apt_repo