---
- name: install postgresql
  apt: pkg={{ item }} state=present
  with_items:
    - postgresql
    - python-psycopg2 # needed for postgresql_user
    - libpq-dev # for pg gem

- name: setup postgresql user
  sudo_user: postgres
  postgresql_user: user=dawn password=NULL role_attr_flags=CREATEDB,SUPERUSER state=present

- name: start postgresql
  service: name=postgresql state=started