---
#- name: install RVM
#  shell: \curl -L https://get.rvm.io | bash -s stable --autolibs=3 creates=~/.rvm

#- name: add user to RVM group
#  sudo: yes
#  user: name={{ user_main }} append=yes groups=rvm

#- name: install {{ ruby }}
#  shell: ~/.rvm/bin/rvm install {{ ruby }} --default

## requires at least 500mb of free RAM
#- name: install rubinius
#  shell: ~/.rvm/bin/rvm install rbx

- name: check ruby version
  shell: ruby -v
  register: ruby_v

- name: ensure we have the build tools and dependencies needed
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
  - build-essential
  - zlib1g-dev
  - libyaml-dev
  - libssl-dev
  - libgdbm-dev
  - libreadline-dev
  - libncurses5-dev
  - libffi-dev
  when: ruby_v.stdout.find(ruby_version) == -1

- name: ensure directory /tmp/ruby is present
  file: state=directory path=/tmp/ruby
  when: ruby_v.stdout.find(ruby_version) == -1

- name: download ruby
  get_url: url=ftp://ftp.ruby-lang.org/pub/ruby/2.1/{{ ruby }}.tar.bz2 dest=/tmp/ruby
  when: ruby_v.stdout.find(ruby_version) == -1

- name: extract ruby
  shell: tar -xf {{ruby}}.tar.bz2 chdir=/tmp/ruby creates={{ ruby }}
  when: ruby_v.stdout.find(ruby_version) == -1

- name: configure ruby
  shell: ./configure --with-readline-dir=/usr/local chdir=/tmp/ruby/{{ ruby }} creates=Makefile
  when: ruby_v.stdout.find(ruby_version) == -1

- name: build ruby
  shell: make chdir=/tmp/ruby/{{ ruby }} creates=ruby
  when: ruby_v.stdout.find(ruby_version) == -1

- name: install ruby
  shell: make install chdir=/tmp/ruby/{{ ruby }} creates=/usr/local/bin/ruby
  when: ruby_v.stdout.find(ruby_version) == -1

# https://github.com/rubygems/rubygems/issues/827
- name: setup system gemrc
  copy: src=gemrc dest=/usr/local/etc/gemrc
