---
- name: download logplex
  git: repo=https://github.com/heroku/logplex.git dest=/opt/logplex

- name: compile logplex
  shell: ./rebar --config public.rebar.config get-deps compile chdir=/opt/logplex


- name: add logplex service to Upstart
  copy: src=logplex/upstart.conf dest=/etc/init/logplex.conf

- name: add redis-logplex config
  copy: src=logplex/redis.conf dest=/etc/redis/redis-logplex.conf

- name: add redis-logplex service to Upstart
  copy: src=logplex/upstart-redis.conf dest=/etc/init/redis-logplex.conf

- name: ensure directory /tmp/ruby is present
  file: state=directory path=/var/lib/redis-logplex user=redis group=redis mode=0755
# mkdir /var/lib/redis-logplex chowned to redis:redis

# enable redis-logplex
# enable logplex




# to build log-shuttle
  # git clone https://github.com/heroku/log-shuttle.git
  # cd log-shuttle
  # go get github.com/kr/godep
  # export PATH=$PATH:$GOPATH/bin
  # godep go build