---
#- name: add erlang to local key chain
#  apt_key: url=http://packages.erlang-solutions.com/debian/erlang_solutions.asc

#- name: add erlang repository
#  apt_repository: repo='deb http://packages.erlang-solutions.com/debian raring contrib' state=present

#- name: install erlang (R16B02)
#  apt: pkg=erlang=1:16.b.2 state=present update_cache=yes

- name: download logplex
  git: repo=https://github.com/heroku/logplex.git dest=/opt/logplex

- name: compile logplex
  shell: >
    executable=/bin/bash source /usr/lib/kerl/installs/default/activate;
    ./rebar --config public.rebar.config get-deps compile chdir=/opt/logplex creates=/opt/logplex/bin/logplex

- name: add logplex service to Upstart
  copy: src=upstart.conf dest=/etc/init/logplex.conf

- name: add redis-logplex config
  copy: src=redis.conf dest=/etc/redis/redis-logplex.conf

- name: add redis-logplex service to Upstart
  copy: src=upstart-redis.conf dest=/etc/init/redis-logplex.conf

- name: ensure directory /var/lib/redis-logplex is present
  file: state=directory path=/var/lib/redis-logplex owner=redis group=redis mode=0755

- name: start redis-logplex
  service: name=redis-logplex state=started

- name: start logplex
  service: name=logplex state=started

# to build log-shuttle
  # git clone https://github.com/heroku/log-shuttle.git
  # cd log-shuttle
  # go get github.com/kr/godep
  # export PATH=$PATH:$GOPATH/bin
  # godep go build