---
- name: spin up redis-logplex
  command: docker run -d -p 6733:6379 --name redis-logplex redis

- name: spin up logplex
  command: docker run -d -p 5432:5432 --name logplex --link redis-logplex:redis dawn/logplex
