---
- name: setup user group
  tags: group_main
  group: name={{ group_main }}
         state=present

- name: create dawn user
  tags: user
  user: name=dawn
        shell=/bin/bash
        state=present
        group=sudo
        groups={{ group_main }}
        password=$1$salt$wEFEXlsqMhUc7RwxISKiy0

- name: create git user
  tags: user
  user: name={{ user_git }}
        state=present
        home={{ path_home_git }}
        shell=/usr/bin/git-shell
        groups={{ group_main }}

- name: setup /home/git access for group_main
  tags: group_main
  sudo: yes
  file: path={{ path_home_git }}
        group={{ group_main }}
        recurse=yes
        state=directory
        mode=0770