---
- name: ensure we have the build tools and dependencies needed
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
  - build-essential
  - libyaml-dev
  - libssl-dev
  - libgdbm-dev
  - libffi-dev

- name: ensure directory /tmp/ruby is present
  file: state=directory path=/tmp/ruby

- name: download ruby
  get_url: url=ftp://ftp.ruby-lang.org/pub/ruby/2.0/{{ ruby }}.tar.bz2 dest=/tmp/ruby

- name: extract ruby
  shell: tar -xf {{ruby}}.tar.bz2 chdir=/tmp/ruby creates={{ ruby }}

- name: configure ruby
  shell: ./configure chdir=/tmp/ruby/{{ ruby }} creates=Makefile

- name: build ruby
  shell: make chdir=/tmp/ruby/{{ ruby }} creates=ruby

- name: install ruby
  shell: make install chdir=/tmp/ruby/{{ ruby }} creates=/usr/local/bin/ruby