# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

DAWN_HOST:         "dawn.dev"
DAWN_APP_HOST:     "dawnapp.dev"
DAWN_LOGPLEX_HOST: "logplex" # used inside the VM, dawn.dev doesn't exist
DAWN_LOGPLEX_URL:  "172.17.42.1" # docker0, parent interface
DAWN_BUILD_TOKEN:  "E1HZojQmOoQdLu3fUHxQMqLmJnrJjTqm"

LOGPLEX_SECRET:   "hd4Dna3UGxqXqtuVkMYF"
LOGPLEX_COOKIE:   "dawnplex"
LOGPLEX_USER:     "dawn"
LOGPLEX_PASSWORD: "salvorhardin"
