---
test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: dawn_test
  template: template0
  pool: 5
  username: dawn
  password:

development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: dawn_development
  template: template0
  pool: 5
  host: localhost
  username: dawn
  password: dawn

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: dawn_production
  template: template0
  pool: 5
  host: localhost
  username: dawn
<<<<<<< HEAD
  password: dawn
=======
  password:
>>>>>>> origin/patches
