development:
  adapter: postgresql
  encoding: unicode
  database: dawn_development
  template: template0
  pool: 5
  username: dawn
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dawn_test
  template: template0
  pool: 5
  username: dawn
  password: