development:
  adapter: postgresql
  encoding: unicode
  database: dawn_development
  template: template0
  pool: 5
  host: localhost
  username: dawn
  password: dawn

test:
  adapter: postgresql
  encoding: unicode
  database: dawn_test
  template: template0
  pool: 5
  host: localhost
  username: dawn
  password: dawn