---
- hosts: all
  remote_user: "{{ lookup('env', 'USER') }}"
  sudo: true
  vars_files:
    - vars/main.yml
    - vars/main.yml
    - vars/service.yml
  roles:
    - { role: root, tags: ["root"] }
    - { role: common,   tags: ["common"]   }
    - { role: erlang,   tags: ["erlang"]   }
    - { role: logplex,  tags: ["logplex"]  }
    - { role: gitlab,   tags: ["gitlab"]   }
    - { role: rails,    tags: ["rails"]    }