---
- hosts: all
  remote_user: "{{ lookup('env', 'USER') }}"
  sudo: true
  vars_files:
    - vars/main.yml
    - vars/service.yml
  roles:
    - { role: root, tags: ["root"] }
    - { role: common,   tags: ["common"]   }
    - { role: erlang,   tags: ["erlang"]   }
    - { role: logplex,  tags: ["logplex"]  }

- hosts: all:!vagrant
  remote_user: "{{ lookup('env', 'USER') }}"
  sudo: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: pull source from repository
      git: repo={{ project_repo }} dest={{ path_app }}
      tags: app-get
    - name: setup app directory
      file: path={{ path_app }}
            owner={{ user_main }}
            state=directory
            mode=0755
      tags: app-get
    - name: give dawn ownership of the app directory
      file: path={{ path_app }}
            owner={{ user_main }}
            group={{ group_main }}
            recurse=yes

- hosts: all
  remote_user: "{{ lookup('env', 'USER') }}"
  sudo: true
  vars_files:
    - vars/main.yml
    - vars/service.yml
  roles:
    - { role: gitlab,   tags: ["gitlab"]   }
    - { role: rails,    tags: ["rails"]    }
