---
- hosts: dawndev
  remote_user: dawn # rename to remote_user in Ansible v1.4
  vars_files:
    - vars/main.yml
  roles:
    - common
  tasks:
    #- name: upgrade packages
    #  apt: upgrade=yes update_cache=yes
    #  sudo: true