---
- hosts: dawndev
  remote_user: dawn # rename to remote_user in Ansible v1.4
  vars_files:
    - vars/main.yml
  roles:
    - { role: common, tags: ["common"] }
    - { role: git,    tags: ["git"]    }
    - { role: rails,  tags: ["rails"]  }