---
- hosts: vagrant
  remote_user: dawn
  vars_files:
    - vars/main.yml
    - vars/service.yml
  roles:
    - { role: common,   tags: ["common"]   }
    - { role: logplex,  tags: ["logplex"]  }
    - { role: git,      tags: ["git"]      }
    - { role: rails,    tags: ["rails"]    }