---
- hosts: all:!vagrant
  remote_user: "{{ lookup('env', 'USER') }}"
  sudo: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: install userspace packages
      apt: update_cache=yes pkg={{ item }} state=present
      tags: [packages]
      with_items:
        - curl
        - git
        - python-pycurl # needed for apt_repo

    - name: pull source from repository
      git: repo={{ project_repo }} dest={{ app_path }} version=dockerify
      tags: app-get

- hosts: all
  remote_user: "{{ lookup('env', 'USER') }}"
  sudo: true
  vars_files:
    - vars/main.yml
  tasks:
  roles:
    - { role: common,   tags: ["common"]   }