---

# playbooks/newhost.yml
#
# This playbook creates initial admin account and ensures that ansible can
# access the server through sudo. You should run it just after new server has
# been installed and connected to the network. Make sure that you can access
# it through ssh on the root account. You might have to provide a password (in
# that case use '-k' switch on the command line).
#
# Usage:
# ansible-playbook playbooks/newhost.yml -k --limit host
#
# After securing access to the server by disabling the password authentication
# in sshd, this playbook is expected to not work correctly.

- hosts: all:!localhost:!vagrant
  remote_user: root
  sudo: no
  gather_facts: False

  tasks:
  - name: Install python support for Ansible
    raw: apt-get -yq install python python-apt

  - name: Gather host facts
    action: setup

  - name: Create admin system group
    group: name=admins system=yes state=present

  - name: Create administrator account
    user: name={{ lookup('env', 'USER') }} state=present shell=/bin/sh groups=admins

  - name: Make sure essential software is installed
    apt: pkg={{ item }} state=latest install_recommends=no
    with_items: [ 'python', 'python-apt', 'sudo', 'lsb-release' ]

  - name: Install ssh public key from current account
    authorized_key: user={{ lookup('env','USER') }} key="{{ lookup('file','~/.ssh/id_rsa.pub') }}"

  - name: Configure admins group access in sudo
    lineinfile: "dest=/etc/sudoers.d/admins state=present create=yes regexp='^%admins' line='%admins ALL=(ALL:ALL) NOPASSWD: SETENV: ALL' owner=root group=root mode=0440"

- hosts: vagrant
  remote_user: vagrant
  sudo: yes
  gather_facts: False

  tasks:
  - name: Install python support for Ansible
    raw: apt-get -yq install python python-apt

  - name: Gather host facts
    action: setup

  - name: Create admin system group
    group: name=admins system=yes state=present

  - name: Create administrator account
    user: name={{ lookup('env', 'USER') }} state=present shell=/bin/sh groups=admins

  - name: Make sure essential software is installed
    apt: pkg={{ item }} state=latest install_recommends=no
    with_items: [ 'python', 'python-apt', 'sudo', 'lsb-release' ]

  - name: Install ssh public key from current account
    authorized_key: user={{ lookup('env','USER') }} key="{{ lookup('file','~/.ssh/id_rsa.pub') }}"

  - name: Configure admins group access in sudo
    lineinfile: "dest=/etc/sudoers.d/admins state=present create=yes regexp='^%admins' line='%admins ALL=(ALL:ALL) NOPASSWD: SETENV: ALL' owner=root group=root mode=0440"
