---
- name: install gem extensions dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - libssl-dev # puma
    - libpq-dev # for pg gem

- name: build dawn/buildstep
  command: docker build -t dawn/buildstep . chdir={{ app_path }}
  sudo_user: "{{ user_main }}"

- name: install global foreman
  command: gem install foreman

- name: gem install bundler
  command: gem install bundler

- name: bundle install
  command: bundle install --path vendor/bundle chdir={{ app_path }}
  tags: bundle-install
  sudo_user: "{{ user_main }}"

- name: setup database
  command: bin/rake db:create db:migrate db:seed chdir={{ app_path }}
  sudo_user: "{{ user_main }}"

- name: setup logplex
  command: script/logplex chdir={{ app_path }}
  sudo_user: "{{ user_main }}"

- name: setup hipache proxying for dawn.dev
  command: script/hipache chdir={{ app_path }}
  sudo_user: "{{ user_main }}"


- name: export Procfile to Upstart
  command: foreman export -f {{ app_path }}/Procfile upstart /etc/init -a dawn chdir={{ app_path }}
  tags: export-services

- name: deploy!
  service: name={{ user_main }} state=started # enabled=yes
  tags: app-deploy