---
- name: install puma dependency
  apt: pkg=libssl-dev state=present

#- name: pull source from repository
#  git: repo={{ project_repo }} dest={{ path_app }}
#  tags: app-get

#- name: setup app directory
#  file: path={{ path_app }}
#        owner={{ user_main }}
#        state=directory
#        mode=0755
#  tags: app-get

- name: build dawn/buildstep
  command: docker build -t dawn/buildstep . chdir={{ path_app }}
  sudo_user: {{ user_main }}

- name: install global foreman
  command: gem install foreman

- name: gem install bundler
  command: gem install bundler

- name: bundle install
  command: bundle install chdir={{ path_app }}
  tags: bundle-install
  sudo_user: {{ user_main }}

- name: setup database
  command: bin/rake db:create db:migrate db:seed chdir={{ path_app }}
  sudo_user: {{ user_main }}

- name: export Procfile to Upstart
  command: foreman export -f {{ path_app }}/Procfile upstart /etc/init -a dawn chdir={{ path_app }}
  tags: export-services

- name: deploy!
  service: name={{ service_name }} state=started # enabled=yes
  tags: app-deploy