---
- name: install gem extensions dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - libssl-dev # puma
    - libpq-dev # for pg gem

- name: build dawn/buildstep
  command: docker build -t dawn/buildstep . chdir={{ path_app }}
  sudo_user: "{{ user_main }}"

- name: install global foreman
  command: gem install foreman

- name: gem install bundler
  command: gem install bundler

- name: bundle install
  command: bundle install --path vendor/bundle chdir={{ path_app }}
  tags: bundle-install
  sudo_user: "{{ user_main }}"

- name: setup database
  command: bin/rake db:create db:migrate db:seed chdir={{ path_app }}
  sudo_user: "{{ user_main }}"

- name: setup logplex
  command: script/logplex chdir={{ path_app }}
  sudo_user: "{{ user_main }}"

- name: setup hipache proxying for dawn.dev
  command: script/hipache chdir={{ path_app }}
  sudo_user: "{{ user_main }}"


- name: export Procfile to Upstart
  command: foreman export -f {{ path_app }}/Procfile upstart /etc/init -a dawn chdir={{ path_app }}
  tags: export-services

- name: deploy!
  service: name={{ service_name }} state=started # enabled=yes
  tags: app-deploy