---
- name: install puma dependency
  sudo: yes
  apt: pkg=libssl-dev state=present

- name: pull source from repository
  git: repo={{ project_repo }} dest={{ path_app }}
  sudo: yes
  tags: app-get

- name: setup app directory
  sudo: yes
  file: path={{ path_app }}
        owner={{ user_main }}
        state=directory
        mode=0755
  tags: app-get

- name: build dawn/buildstep
  command: docker build -t dawn/buildstep . chdir={{ path_app }}

- name: gem install bundler
  command: gem install bundler
  sudo: yes

- name: bundle install
  command: bundle install chdir={{ path_app }}
  tags: bundle-install

- name: export Procfile to Upstart
  sudo: yes
  command: foreman export -f {{ path_app }}/Procfile upstart /etc/init -a dawn chdir={{ path_app }}
  tags: export-services

- name: deploy!
  sudo: yes
  service: name={{ service_name }} state=started # enabled=yes
  tags: app-deploy