- name: install puma dependency
  apt: pkg=libssl-dev state=present

- name: bundle install
  command: bundle install

- name: export Procfile to Upstart
  command: foreman export upstart /etc/init -a dawn
  sudo: yes

- name: deploy!
  service: name=dawn state=started # enabled=yes
